arm, imx: fix spl compile for mxs boards
files in arch/arm/imx-common/ get not yet compiled for
SPL case as "mxs" is missing in filter rule.

Signed-off-by: Heiko Schocher <hs@denx.de>
Patch-cc: Daniel Schwierzeck <daniel.schwierzeck@gmail.com>
Patch-cc: Masahiro Yamada <yamada.m@jp.panasonic.com>
Patch-cc: Stefano Babic <sbabic@denx.de>

Commit-notes:

Fixes build error on for example the mx28evk_auart_console board:

Building mx28evk_auart_console board...
   text    data     bss     dec     hex filename
 442689   36826  327648  807163   c50fb ./u-boot
make[1]: *** [spl/u-boot-spl] Error 1
make: *** [spl/u-boot-spl] Error 2
drivers/serial/built-in.o: In function `mxs_auart_init':
/home/hs/zug/u-boot/drivers/serial/mxs_auart.c:84: undefined reference to `mxs_reset_block'
make[1]: *** [spl/u-boot-spl] Error 1
make: *** [spl/u-boot-spl] Error 2
make: *** Warte auf noch nicht beendete Prozesse...
END