x86: dts: fix DTC unit name warnings
Fix following DTC warnings for all x86 boards.

There was a warning like:
Warning (unit_address_vs_reg): Node /microcode/update@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /microcode/update@1 has a unit name, but no reg property

I replaced "udpate@" with "update_". Please test
this patch

Signed-off-by: Heiko Schocher <hs@denx.de>
Series-to: uboot
Patch-cc: sjg
Patch-cc: Roger Meier <r.meier@siemens.com>

Commit-notes:
This warnings pop up with the DTC compiler:
$ /tmp/dtc/dtc -v
Version: DTC 1.4.1-gbeef80b8

This fixes the compile warnings for:
https://travis-ci.org/u-boot/u-boot/jobs/122880432

see:

Tested with sandbox, following steps work as before:

make sandbox_defconfig
make
./u-boot -d u-boot.dtb

but "ut all" drops warnings ... but this patch introduced
no new warnings ...

output of test/py :

+make O=/home/hs/zug/travis/u-boot.git/build-sandbox -s sandbox_defconfig
+make O=/home/hs/zug/travis/u-boot.git/build-sandbox -s -j8
=================================================================================== test session starts ====================================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/hs/zug/travis/u-boot.git, inifile:
collected 204 items

test/py/tests/test_000_version.py .
test/py/tests/test_dfu.py s
test/py/tests/test_env.py ........
test/py/tests/test_help.py .
test/py/tests/test_hush_if_test.py .......................................................
test/py/tests/test_md.py ..
test/py/tests/test_net.py .ssss
test/py/tests/test_sandbox_exit.py ..
test/py/tests/test_shell_basics.py ....
test/py/tests/test_sleep.py .
test/py/tests/test_ums.py s
test/py/tests/test_unknown_cmd.py .
test/py/tests/test_ut.py ......................................................................................F...................................

========================================================================================= FAILURES =========================================================================================
_________________________________________________________________________________ test_ut[ut_dm_spi_flash] _________________________________________________________________________________

u_boot_console = <u_boot_console_sandbox.ConsoleSandbox object at 0x7f68ce2852d0>, ut_subtest = 'dm spi_flash'

    def test_ut(u_boot_console, ut_subtest):
        """Execute a "ut" subtest."""

        output = u_boot_console.run_command('ut ' + ut_subtest)
>       assert output.endswith('Failures: 0')
E       assert <built-in method endswith of str object at 0x7f68cf10e6d0>('Failures: 0')
E        +  where <built-in method endswith of str object at 0x7f68cf10e6d0> = 'Test: dm_test_spi_flash\r\r\n2097152 bytes written in 24 ms (83.3 MiB/s)\r\r\nSF: Detected M25P16 with page size 256 ...d_list( "sb save hostfs - 0 spi.bin 200000;" "sf probe;" "sf test 0 10000", -1, 0): Expected 0, got 1\r\r\nFailures: 1'.endswith

test/py/tests/test_ut.py:29: AssertionError
----------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------
=> ut dm spi_flash
Test: dm_test_spi_flash
2097152 bytes written in 24 ms (83.3 MiB/s)
SF: Detected M25P16 with page size 256 Bytes, erase size 64 KiB, total 2 MiB
SPI flash test:
SF: Timeout!
Erase failed
Test failed
../test/dm/sf.c:34, dm_test_spi_flash(): 0 == run_command_list( "sb save hostfs - 0 spi.bin 200000;" "sf probe;" "sf test 0 10000", -1, 0): Expected 0, got 1
Failures: 1
=>
===================================================================== 1 failed, 197 passed, 6 skipped in 12.03 seconds =====================================================================
pollux:u-boot.git hs [20160415_2] $

This error is also without this patch ... may I find
time to fix it too...

END